#!/bin/sh
#
# pi_make_install_package <package_version>
#
# z.B.:
# pi_make_install_package 1.0.0
#

./pi_set_install_file_settings
tar --exclude PIPython.zip -cjf PIPython-$1-INSTALL.tar.bz2 PIPython

